#!/bin/bash

# $IMAGE_NAME var is injected into the build so the tag is correct.
IMAGE_REPO=${IMAGE_NAME%:*}
IMAGE_TAG=${IMAGE_NAME#*:}

SPARK_VERSION=${IMAGE_TAG:0:1}
if [ ${SPARK_VERSION} = "3" ]; then
    OPENJDK_VERSION=11
else
    OPENJDK_VERSION=8
fi

# Trigger build
docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
             --build-arg SPARK_VERSION=$IMAGE_TAG \
             --build-arg OPENJDK_VERSION=$OPENJDK_VERSION \
             -t $DOCKER_REPO:${DOCKER_TAG//,/ -t $DOCKER_REPO:} .