#!/bin/bash

# $IMAGE_NAME var is injected into the build so the tag is correct.
IMAGE_REPO=${IMAGE_NAME%:*}
IMAGE_TAG=${IMAGE_NAME#*:}

# Retag to latest
if [ "$IMAGE_TAG" = "2.2.1" ]; then
    docker tag $IMAGE_NAME ${IMAGE_REPO}:latest
    docker push ${IMAGE_REPO}:latest
fi